from django.http import JsonResponse
import google.generativeai as genai
from dotenv import load_dotenv
import os,random
from .. import models
load_dotenv()
AI_API_KEY = os.getenv('AI_API_KEY')
genai.configure(api_key=AI_API_KEY)
model = genai.GenerativeModel("gemini-2.5-flash")

def get_ai_interpretation(spread, spread_type="3-card"):
    prompt = f"""
    You are a professional tarot reader.
    The user drew a {spread_type} tarot spread with these cards:
    {spread}
    Please write a meaningful interpretation:
    - Connect the cards together (not just separate meanings).
    - Explain the story of Past, Present, Future.
    - Be clear, warm, and inspiring.
    """
    response = model.generate_content(prompt)
    return response.text.strip()


TAROT_CARDS = [
    # ---- Major Arcana (22) ----
    {"name": "The Fool", "suit": "Major Arcana",
     "meaning_upright": "New beginnings, optimism, innocence, trust in life.",
     "meaning_reversed": "Naivety, poor judgment, recklessness, foolishness.",
     "image": "tarot/fool.jpg"},
    {"name": "The Magician", "suit": "Major Arcana",
     "meaning_upright": "Manifestation, power, resourcefulness, inspired action.",
     "meaning_reversed": "Manipulation, poor planning, untapped talents.",
     "image": "tarot/magician.jpg"},
    {"name": "The High Priestess", "suit": "Major Arcana",
     "meaning_upright": "Intuition, sacred knowledge, divine feminine, the subconscious mind.",
     "meaning_reversed": "Secrets, disconnected from intuition, withdrawal, silence.",
     "image": "tarot/high_priestess.jpg"},
    {"name": "The Empress", "suit": "Major Arcana",
     "meaning_upright": "Femininity, beauty, nature, nurturing, abundance.",
     "meaning_reversed": "Creative block, dependence on others.",
     "image": "tarot/empress.jpg"},
    {"name": "The Emperor", "suit": "Major Arcana",
     "meaning_upright": "Authority, structure, control, fatherhood.",
     "meaning_reversed": "Domination, excessive control, rigidity, inflexibility.",
     "image": "tarot/emperor.jpg"},
    {"name": "The Hierophant", "suit": "Major Arcana",
     "meaning_upright": "Spiritual wisdom, religious beliefs, conformity, tradition.",
     "meaning_reversed": "Personal beliefs, freedom, challenging tradition.",
     "image": "tarot/hierophant.jpg"},
    {"name": "The Lovers", "suit": "Major Arcana",
     "meaning_upright": "Love, harmony, partnerships, choices.",
     "meaning_reversed": "Disharmony, imbalance, misalignment of values.",
     "image": "tarot/lovers.jpg"},
    {"name": "The Chariot", "suit": "Major Arcana",
     "meaning_upright": "Control, willpower, success, action, determination.",
     "meaning_reversed": "Self-discipline, opposition, lack of direction.",
     "image": "tarot/chariot.jpg"},
    {"name": "Strength", "suit": "Major Arcana",
     "meaning_upright": "Courage, persuasion, influence, compassion.",
     "meaning_reversed": "Self-doubt, weakness, insecurity.",
     "image": "tarot/strength.jpg"},
    {"name": "The Hermit", "suit": "Major Arcana",
     "meaning_upright": "Soul-searching, introspection, being alone, inner guidance.",
     "meaning_reversed": "Isolation, loneliness, withdrawal.",
     "image": "tarot/hermit.jpg"},
    {"name": "Wheel of Fortune", "suit": "Major Arcana",
     "meaning_upright": "Good luck, karma, life cycles, destiny, turning points.",
     "meaning_reversed": "Bad luck, resistance to change, breaking cycles.",
     "image": "tarot/wheel_of_fortune.jpg"},
    {"name": "Justice", "suit": "Major Arcana",
     "meaning_upright": "Justice, fairness, truth, law.",
     "meaning_reversed": "Unfairness, lack of accountability, dishonesty.",
     "image": "tarot/justice.jpg"},
    {"name": "The Hanged Man", "suit": "Major Arcana",
     "meaning_upright": "Pause, surrender, letting go, new perspectives.",
     "meaning_reversed": "Delays, resistance, stalling, indecision.",
     "image": "tarot/hanged_man.jpg"},
    {"name": "Death", "suit": "Major Arcana",
     "meaning_upright": "Endings, change, transformation, transition.",
     "meaning_reversed": "Resistance to change, personal transformation, inner purging.",
     "image": "tarot/death.jpg"},
    {"name": "Temperance", "suit": "Major Arcana",
     "meaning_upright": "Balance, moderation, patience, purpose.",
     "meaning_reversed": "Imbalance, excess, lack of long-term vision.",
     "image": "tarot/temperance.jpg"},
    {"name": "The Devil", "suit": "Major Arcana",
     "meaning_upright": "Shadow self, attachment, addiction, restriction, sexuality.",
     "meaning_reversed": "Releasing limiting beliefs, exploring dark thoughts, detachment.",
     "image": "tarot/devil.jpg"},
    {"name": "The Tower", "suit": "Major Arcana",
     "meaning_upright": "Sudden change, upheaval, chaos, revelation, awakening.",
     "meaning_reversed": "Personal transformation, fear of change, averting disaster.",
     "image": "tarot/tower.jpg"},
    {"name": "The Star", "suit": "Major Arcana",
     "meaning_upright": "Hope, faith, purpose, renewal, spirituality.",
     "meaning_reversed": "Lack of faith, despair, disconnection.",
     "image": "tarot/star.jpg"},
    {"name": "The Moon", "suit": "Major Arcana",
     "meaning_upright": "Illusion, fear, anxiety, subconscious, intuition.",
     "meaning_reversed": "Release of fear, confusion, misinterpretation.",
     "image": "tarot/moon.jpg"},
    {"name": "The Sun", "suit": "Major Arcana",
     "meaning_upright": "Positivity, fun, warmth, success, vitality.",
     "meaning_reversed": "Inner child, feeling down, overly optimistic.",
     "image": "tarot/sun.jpg"},
    {"name": "Judgement", "suit": "Major Arcana",
     "meaning_upright": "Judgement, rebirth, inner calling, absolution.",
     "meaning_reversed": "Self-doubt, inner critic, ignoring the call.",
     "image": "tarot/judgement.jpg"},
    {"name": "The World", "suit": "Major Arcana",
     "meaning_upright": "Completion, integration, accomplishment, travel.",
     "meaning_reversed": "Seeking closure, delays, short-cuts.",
     "image": "tarot/world.jpg"},

    # ---- Minor Arcana: Cups (14) ----
    {"name": "Ace of Cups", "suit": "Cups",
     "meaning_upright": "Love, new relationships, compassion, creativity.",
     "meaning_reversed": "Self-love, repressed emotions, emotional blockages.",
     "image": "tarot/ace_cups.jpg"},
    {"name": "Two of Cups", "suit": "Cups",
     "meaning_upright": "Unified love, partnership, attraction, mutual respect.",
     "meaning_reversed": "Breakups, imbalance, disharmony.",
     "image": "tarot/two_cups.jpg"},
    {"name": "Three of Cups", "suit": "Cups",
     "meaning_upright": "Celebration, friendship, creativity, community.",
     "meaning_reversed": "Gossip, isolation, overindulgence.",
     "image": "tarot/three_cups.jpg"},
    {"name": "Four of Cups", "suit": "Cups",
     "meaning_upright": "Meditation, apathy, contemplation, disconnection.",
     "meaning_reversed": "Boredom, missed opportunities, being aloof.",
     "image": "tarot/four_cups.jpg"},
    {"name": "Five of Cups", "suit": "Cups",
     "meaning_upright": "Regret, failure, disappointment, pessimism.",
     "meaning_reversed": "Acceptance, moving on, finding peace.",
     "image": "tarot/five_cups.jpg"},
    {"name": "Six of Cups", "suit": "Cups",
     "meaning_upright": "Revisiting the past, childhood memories, innocence.",
     "meaning_reversed": "Stuck in the past, naivety, unrealistic expectations.",
     "image": "tarot/six_cups.jpg"},
    {"name": "Seven of Cups", "suit": "Cups",
     "meaning_upright": "Opportunities, choices, wishful thinking, illusion.",
     "meaning_reversed": "Clarity, reality check, temptation.",
     "image": "tarot/seven_cups.jpg"},
    {"name": "Eight of Cups", "suit": "Cups",
     "meaning_upright": "Abandonment, withdrawal, retreat, moving on.",
     "meaning_reversed": "Avoidance, fear of change, aimless drifting.",
     "image": "tarot/eight_cups.jpg"},
    {"name": "Nine of Cups", "suit": "Cups",
     "meaning_upright": "Contentment, satisfaction, gratitude, wish come true.",
     "meaning_reversed": "Dissatisfaction, indulgence, superficiality.",
     "image": "tarot/nine_cups.jpg"},
    {"name": "Ten of Cups", "suit": "Cups",
     "meaning_upright": "Happiness, family, harmony, fulfillment.",
     "meaning_reversed": "Broken relationships, disharmony, misaligned values.",
     "image": "tarot/ten_cups.jpg"},
    {"name": "Page of Cups", "suit": "Cups",
     "meaning_upright": "Creative opportunities, curiosity, possibility, intuition.",
     "meaning_reversed": "Emotional immaturity, insecurity, disappointment.",
     "image": "tarot/page_cups.jpg"},
    {"name": "Knight of Cups", "suit": "Cups",
     "meaning_upright": "Romance, charm, imagination, beauty.",
     "meaning_reversed": "Overly idealistic, jealousy, moodiness.",
     "image": "tarot/knight_cups.jpg"},
    {"name": "Queen of Cups", "suit": "Cups",
     "meaning_upright": "Compassionate, caring, emotionally stable, intuitive.",
     "meaning_reversed": "Codependency, emotional insecurity.",
     "image": "tarot/queen_cups.jpg"},
    {"name": "King of Cups", "suit": "Cups",
     "meaning_upright": "Emotional balance, compassion, diplomacy.",
     "meaning_reversed": "Manipulation, moodiness, volatility.",
     "image": "tarot/king_cups.jpg"},

    # ---- Minor Arcana: Wands (14) ----
    {"name": "Ace of Wands", "suit": "Wands",
     "meaning_upright": "Inspiration, new opportunities, growth, potential.",
     "meaning_reversed": "Delays, lack of motivation, weighed down.",
     "image": "tarot/ace_wands.jpg"},
    {"name": "Two of Wands", "suit": "Wands",
     "meaning_upright": "Planning, making decisions, future planning, progress.",
     "meaning_reversed": "Fear of change, playing safe, bad planning.",
     "image": "tarot/two_wands.jpg"},
    {"name": "Three of Wands", "suit": "Wands",
     "meaning_upright": "Progress, expansion, foresight, overseas opportunities.",
     "meaning_reversed": "Delays, lack of foresight, unexpected obstacles.",
     "image": "tarot/three_wands.jpg"},
    {"name": "Four of Wands", "suit": "Wands",
     "meaning_upright": "Celebration, harmony, homecoming, community.",
     "meaning_reversed": "Lack of support, instability, conflict at home.",
     "image": "tarot/four_wands.jpg"},
    {"name": "Five of Wands", "suit": "Wands",
     "meaning_upright": "Conflict, disagreements, competition, tension.",
     "meaning_reversed": "Avoiding conflict, compromise, harmony.",
     "image": "tarot/five_wands.jpg"},
    {"name": "Six of Wands", "suit": "Wands",
     "meaning_upright": "Success, recognition, victory, progress.",
     "meaning_reversed": "Ego, lack of recognition, fall from grace.",
     "image": "tarot/six_wands.jpg"},
    {"name": "Seven of Wands", "suit": "Wands",
     "meaning_upright": "Challenge, competition, standing your ground, perseverance.",
     "meaning_reversed": "Giving up, overwhelmed, lack of confidence.",
     "image": "tarot/seven_wands.jpg"},
    {"name": "Eight of Wands", "suit": "Wands",
     "meaning_upright": "Movement, fast progress, rapid action.",
     "meaning_reversed": "Delays, frustration, resisting change.",
     "image": "tarot/eight_wands.jpg"},
    {"name": "Nine of Wands", "suit": "Wands",
     "meaning_upright": "Resilience, courage, persistence, test of faith.",
     "meaning_reversed": "Exhaustion, fatigue, giving up.",
     "image": "tarot/nine_wands.jpg"},
    {"name": "Ten of Wands", "suit": "Wands",
     "meaning_upright": "Burden, responsibility, hard work, stress.",
     "meaning_reversed": "Burnout, release of burden, doing it all alone.",
     "image": "tarot/ten_wands.jpg"},
    {"name": "Page of Wands", "suit": "Wands",
     "meaning_upright": "Inspiration, ideas, free spirit, new beginnings.",
     "meaning_reversed": "Lack of direction, procrastination, immaturity.",
     "image": "tarot/page_wands.jpg"},
    {"name": "Knight of Wands", "suit": "Wands",
     "meaning_upright": "Energy, passion, inspired action, adventure.",
     "meaning_reversed": "Haste, scattered energy, delays, arrogance.",
     "image": "tarot/knight_wands.jpg"},
    {"name": "Queen of Wands", "suit": "Wands",
     "meaning_upright": "Confidence, independence, determination, charisma.",
     "meaning_reversed": "Jealousy, selfishness, insecurity.",
     "image": "tarot/queen_wands.jpg"},
    {"name": "King of Wands", "suit": "Wands",
     "meaning_upright": "Leadership, vision, entrepreneurship, honor.",
     "meaning_reversed": "Impulsiveness, domineering, ruthless.",
     "image": "tarot/king_wands.jpg"},

    # ---- Minor Arcana: Swords (14) ----
    {"name": "Ace of Swords", "suit": "Swords",
     "meaning_upright": "Breakthroughs, clarity, new ideas, mental clarity.",
     "meaning_reversed": "Confusion, chaos, lack of clarity.",
     "image": "tarot/ace_swords.jpg"},
    {"name": "Two of Swords", "suit": "Swords",
     "meaning_upright": "Indecision, choices, stalemate, difficult decisions.",
     "meaning_reversed": "Lesser of two evils, indecision, confusion.",
     "image": "tarot/two_swords.jpg"},
    {"name": "Three of Swords", "suit": "Swords",
     "meaning_upright": "Heartbreak, grief, sorrow, betrayal.",
     "meaning_reversed": "Releasing pain, optimism, forgiveness.",
     "image": "tarot/three_swords.jpg"},
    {"name": "Four of Swords", "suit": "Swords",
     "meaning_upright": "Rest, relaxation, recovery, contemplation.",
     "meaning_reversed": "Exhaustion, burnout, deep contemplation.",
     "image": "tarot/four_swords.jpg"},
    {"name": "Five of Swords", "suit": "Swords",
     "meaning_upright": "Conflict, defeat, betrayal, loss.",
     "meaning_reversed": "Reconciliation, making amends, past resentment.",
     "image": "tarot/five_swords.jpg"},
    {"name": "Six of Swords", "suit": "Swords",
     "meaning_upright": "Transition, change, rite of passage, releasing baggage.",
     "meaning_reversed": "Resistance to change, emotional baggage.",
     "image": "tarot/six_swords.jpg"},
    {"name": "Seven of Swords", "suit": "Swords",
     "meaning_upright": "Deception, trickery, strategy, betrayal.",
     "meaning_reversed": "Coming clean, rethinking approach, deception exposed.",
     "image": "tarot/seven_swords.jpg"},
    {"name": "Eight of Swords", "suit": "Swords",
     "meaning_upright": "Restriction, victim mentality, limitation, fear.",
     "meaning_reversed": "Freedom, release, empowerment.",
     "image": "tarot/eight_swords.jpg"},
    {"name": "Nine of Swords", "suit": "Swords",
     "meaning_upright": "Anxiety, fear, depression, nightmares.",
     "meaning_reversed": "Hope, reaching out, inner turmoil.",
     "image": "tarot/nine_swords.jpg"},
    {"name": "Ten of Swords", "suit": "Swords",
     "meaning_upright": "Painful endings, betrayal, loss, crisis.",
     "meaning_reversed": "Recovery, regeneration, resisting an inevitable end.",
     "image": "tarot/ten_swords.jpg"},
    {"name": "Page of Swords", "suit": "Swords",
     "meaning_upright": "Curiosity, mental agility, new ideas, communication.",
     "meaning_reversed": "Deception, manipulation, lack of planning.",
     "image": "tarot/page_swords.jpg"},
    {"name": "Knight of Swords", "suit": "Swords",
     "meaning_upright": "Ambition, drive, determination, assertiveness.",
     "meaning_reversed": "Impatience, recklessness, hostility.",
     "image": "tarot/knight_swords.jpg"},
    {"name": "Queen of Swords", "suit": "Swords",
     "meaning_upright": "Perceptive, independent, direct communication.",
     "meaning_reversed": "Cold-hearted, cruel, overly critical.",
     "image": "tarot/queen_swords.jpg"},
    {"name": "King of Swords", "suit": "Swords",
     "meaning_upright": "Mental clarity, authority, truth, intellectual power.",
     "meaning_reversed": "Manipulation, abuse of power, irrationality.",
     "image": "tarot/king_swords.jpg"},

    # ---- Minor Arcana: Pentacles (14) ----
    {"name": "Ace of Pentacles", "suit": "Pentacles",
     "meaning_upright": "Manifestation, new financial opportunities, prosperity.",
     "meaning_reversed": "Lost opportunities, lack of planning, greed.",
     "image": "tarot/ace_pentacles.jpg"},
    {"name": "Two of Pentacles", "suit": "Pentacles",
     "meaning_upright": "Balance, adaptability, time management, priorities.",
     "meaning_reversed": "Imbalance, disorganization, poor planning.",
     "image": "tarot/two_pentacles.jpg"},
    {"name": "Three of Pentacles", "suit": "Pentacles",
     "meaning_upright": "Teamwork, collaboration, building, learning.",
     "meaning_reversed": "Disharmony, misalignment, poor teamwork.",
     "image": "tarot/three_pentacles.jpg"},
    {"name": "Four of Pentacles", "suit": "Pentacles",
     "meaning_upright": "Control, stability, security, saving money.",
     "meaning_reversed": "Greed, possessiveness, financial insecurity.",
     "image": "tarot/four_pentacles.jpg"},
    {"name": "Five of Pentacles", "suit": "Pentacles",
     "meaning_upright": "Hardship, poverty, financial loss, insecurity.",
     "meaning_reversed": "Recovery from loss, spiritual poverty.",
     "image": "tarot/five_pentacles.jpg"},
    {"name": "Six of Pentacles", "suit": "Pentacles",
     "meaning_upright": "Giving, receiving, generosity, sharing wealth.",
     "meaning_reversed": "Selfishness, debt, inequality.",
     "image": "tarot/six_pentacles.jpg"},
    {"name": "Seven of Pentacles", "suit": "Pentacles",
     "meaning_upright": "Long-term view, hard work, perseverance, investment.",
     "meaning_reversed": "Short-term focus, limited success, frustration.",
     "image": "tarot/seven_pentacles.jpg"},
    {"name": "Eight of Pentacles", "suit": "Pentacles",
     "meaning_upright": "Apprenticeship, mastery, skill development, diligence.",
     "meaning_reversed": "Perfectionism, lack of focus, uninspired work.",
     "image": "tarot/eight_pentacles.jpg"},
    {"name": "Nine of Pentacles", "suit": "Pentacles",
     "meaning_upright": "Luxury, self-sufficiency, financial independence.",
     "meaning_reversed": "Overinvestment in work, hustling, setbacks.",
     "image": "tarot/nine_pentacles.jpg"},
    {"name": "Ten of Pentacles", "suit": "Pentacles",
     "meaning_upright": "Wealth, financial security, family, long-term success.",
     "meaning_reversed": "Financial failure, loneliness, loss.",
     "image": "tarot/ten_pentacles.jpg"},
    {"name": "Page of Pentacles", "suit": "Pentacles",
     "meaning_upright": "Manifestation, new job, learning, financial opportunity.",
     "meaning_reversed": "Procrastination, lack of commitment, foolishness.",
     "image": "tarot/page_pentacles.jpg"},
    {"name": "Knight of Pentacles", "suit": "Pentacles",
     "meaning_upright": "Hard work, responsibility, productivity, routine.",
     "meaning_reversed": "Laziness, boredom, work without reward.",
     "image": "tarot/knight_pentacles.jpg"},
    {"name": "Queen of Pentacles", "suit": "Pentacles",
     "meaning_upright": "Nurturing, practical, financial security, prosperity.",
     "meaning_reversed": "Self-centeredness, imbalance in work/home.",
     "image": "tarot/queen_pentacles.jpg"},
    {"name": "King of Pentacles", "suit": "Pentacles",
     "meaning_upright": "Wealth, business, leadership, security, discipline.",
     "meaning_reversed": "Greed, indulgence, stubbornness, materialism.",
     "image": "tarot/king_pentacles.jpg"},
]

def load_cards():
    for card in TAROT_CARDS:
        models.TarotCard.objects.get_or_create(
            name=card["name"],
            defaults={
                "suit": card["suit"],
                "meaning_upright": card["meaning_upright"],
                "meaning_reversed": card["meaning_reversed"],
                "image": card["image"],
            },
        )
