# Generated by Django 5.2.6 on 2025-09-08 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_time', models.TimeField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=128, null=True)),
                ('birth_tz', models.CharField(choices=[('Asia/Kolkata', 'Asia/Kolkata (UTC+5:30)'), ('UTC', 'UTC'), ('America/New_York', 'America/New_York (UTC-5)'), ('Europe/London', 'Europe/London (UTC+0)'), ('Asia/Dubai', 'Asia/Dubai (UTC+4)'), ('Australia/Sydney', 'Australia/Sydney (UTC+10)')], default='Asia/Kolkata', max_length=64)),
                ('system', models.CharField(choices=[('vedic', 'Vedic Astrology'), ('western', 'Western Astrology'), ('chinese', 'Chinese Astrology')], default='vedic', max_length=16)),
                ('birth_lat', models.FloatField(blank=True, null=True)),
                ('birth_lng', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
