# Generated by Django 5.2.6 on 2025-09-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarotCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('suit', models.CharField(max_length=50)),
                ('meaning_upright', models.TextField()),
                ('meaning_reversed', models.TextField()),
                ('image', models.ImageField(upload_to='tarot/')),
            ],
        ),
    ]
