# Generated by Django 5.2.6 on 2025-09-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarotcard',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
