# Generated by Django 5.2.6 on 2025-10-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_userprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
